#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("fitfam.Resource", IsApplication=true)]

namespace fitfam
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::fitfam.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::fitfam.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::fitfam.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::fitfam.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_custom1_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int theme_devicedefault_background = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int clock = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int face = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fitfamLogo1smaller = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gold_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int gold_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gold_plate = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int home = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int message = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int actionMenuView1 = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int autoCompleteTextView1 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int autoCompleteTextView2 = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int button1 = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int button2 = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int button3 = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int button4 = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int imageButton1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int imageButton2 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int imageButton3 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int imageButton4 = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int imageView1 = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int imageView5 = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout1 = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int multiAutoCompleteTextView1 = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int space1 = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int space2 = 2131165202;
			
			// aapt resource value: 0x7f070006
			public const int textView1 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int textView2 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int textView3 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int textView4 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int textView5 = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Findafamform = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Homepage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_Custom = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Theme_Custom1 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
